name: Aqueduct_ORM_Generator
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: angusgow <angus.gow@flowfoundry.io>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  dart_postgres_wrapper: ^1.0.9
  csv: ^4.0.3
  postgres: ^1.0.2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
